import 'package:bug/mytabbarexample.dart';
import 'package:bug/mydrawer.dart';
import 'package:flutter/material.dart';
import 'package:bug/mygeneric.dart';
import 'package:bug/mylayout.dart';
import 'package:bug/myhomepage.dart';
import 'package:bug/helloworld.dart';
import 'package:bug/url_launcher.dart';
import 'package:bug/myprovider.dart';
import 'package:bug/myhttp.dart';
import 'package:bug/myhttpclient.dart';
import 'package:bug/trycatchfinally.dart';
import 'package:bug/myscaffold.dart';
import 'package:bug/myapp.dart';
import 'package:bug/myroute.dart';
import 'floatingactionbutton.dart';
import 'myacitvityindicator.dart';
import 'myalertdialog.dart';
import 'mycard.dart';
import 'mycupertinobutton.dart';
import 'mycupertino.dart';
import 'mycuptertinoalertdialog.dart';
import 'myflatbutton.dart';
import 'mypopupmenubutton.dart';
import 'mysimpledialog.dart';
import 'mysnackbar.dart';
import 'mytextfield.dart';
import 'myboxsizehandle.dart';
import 'mylist.dart';


void main() {
  // runApp(MyApp());
  // runApp(UrlLauncher());
  // runApp(MyProvider());
  // runApp(MyHttp());
  // runApp(MyHttpClient());
  // runApp(TryCatchFinally());
  // runApp(MyGeneric());
  // runApp(MyLayout());
  // runApp(MyScaffold());
  // runApp(MyRoute());
  // runApp(MyTabBarExample());
  // runApp(MyDrawer());
  // runApp(MyFloatingActionButton());
  // runApp(MyFlatButton());
  // runApp(MyPopupMenuButton());
  // runApp(MySimpleDialog());
  // runApp(MyAlertDialog());
  // runApp(MySnackBar());
  // runApp(MyTextField());
  // runApp(MyCard());
  // runApp(MyActivityIndicator());
  // runApp(MyCupertinoAlertDialog());
  // runApp(MyCupertinoButton());
  // runApp(MyCupertino());
  // runApp(MyBoxsizeHandle());
  runApp(MyList());
}

